// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attempts.sql

package sqlc

import (
	"context"
	"time"
)

const createAttempt = `-- name: CreateAttempt :one
INSERT INTO attempts (
    feedback_id,
    user_challenge_id,
    status
)
VALUES (?, ?, ?)
RETURNING id, user_challenge_id, feedback_id, status, created_at, updated_at
`

type CreateAttemptParams struct {
	FeedbackID      interface{}
	UserChallengeID int64
	Status          string
}

func (q *Queries) CreateAttempt(ctx context.Context, arg CreateAttemptParams) (Attempt, error) {
	row := q.db.QueryRowContext(ctx, createAttempt, arg.FeedbackID, arg.UserChallengeID, arg.Status)
	var i Attempt
	err := row.Scan(
		&i.ID,
		&i.UserChallengeID,
		&i.FeedbackID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserAttemptsByChallengeId = `-- name: GetUserAttemptsByChallengeId :many
SELECT attempts.id, user_challenge_id, feedback_id, attempts.status, attempts.created_at, attempts.updated_at, user_challenges.id, user_id, challenge_id, user_challenges.status, user_challenges.created_at, user_challenges.updated_at, completed_at
FROM attempts
JOIN user_challenges ON attempts.user_challenge_id = user_challenges.id
WHERE user_challenges.user_id = ? AND user_challenges.challenge_id = ?
ORDER BY attempts.created_at DESC
`

type GetUserAttemptsByChallengeIdParams struct {
	UserID      int64
	ChallengeID int64
}

type GetUserAttemptsByChallengeIdRow struct {
	ID              int64
	UserChallengeID int64
	FeedbackID      interface{}
	Status          string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	ID_2            int64
	UserID          int64
	ChallengeID     int64
	Status_2        string
	CreatedAt_2     time.Time
	UpdatedAt_2     time.Time
	CompletedAt     interface{}
}

// This query fetches the attemps made by a specific user for a specific challenge.
// It can be used to track the progress of a user on a particular challenge
// It is obtained joinning the table user_challenges with the attempts table, filtering by user_id and challenge_id.
func (q *Queries) GetUserAttemptsByChallengeId(ctx context.Context, arg GetUserAttemptsByChallengeIdParams) ([]GetUserAttemptsByChallengeIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserAttemptsByChallengeId, arg.UserID, arg.ChallengeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserAttemptsByChallengeIdRow
	for rows.Next() {
		var i GetUserAttemptsByChallengeIdRow
		if err := rows.Scan(
			&i.ID,
			&i.UserChallengeID,
			&i.FeedbackID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ID_2,
			&i.UserID,
			&i.ChallengeID,
			&i.Status_2,
			&i.CreatedAt_2,
			&i.UpdatedAt_2,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
