// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: challenges.sql

package sqlc

import (
	"context"
)

const createChallenge = `-- name: CreateChallenge :one
INSERT INTO challenges (
    name,
    description,
    difficulty,
    type,
    target_pattern,
    user_id
)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, name, description, difficulty, type, target_pattern, user_id, created_at, updated_at
`

type CreateChallengeParams struct {
	Name          string `json:"name"`
	Description   string `json:"description"`
	Difficulty    int64  `json:"difficulty"`
	Type          string `json:"type"`
	TargetPattern string `json:"target_pattern"`
	UserID        int64  `json:"user_id"`
}

// CreateChallenge
//
//	INSERT INTO challenges (
//	    name,
//	    description,
//	    difficulty,
//	    type,
//	    target_pattern,
//	    user_id
//	)
//	VALUES (?, ?, ?, ?, ?, ?)
//	RETURNING id, name, description, difficulty, type, target_pattern, user_id, created_at, updated_at
func (q *Queries) CreateChallenge(ctx context.Context, arg CreateChallengeParams) (Challenge, error) {
	row := q.queryRow(ctx, q.createChallengeStmt, createChallenge,
		arg.Name,
		arg.Description,
		arg.Difficulty,
		arg.Type,
		arg.TargetPattern,
		arg.UserID,
	)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Difficulty,
		&i.Type,
		&i.TargetPattern,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChallengeById = `-- name: GetChallengeById :one
SELECT id, name, description, difficulty, type, target_pattern, user_id, created_at, updated_at
FROM challenges
WHERE id = ?
`

// GetChallengeById
//
//	SELECT id, name, description, difficulty, type, target_pattern, user_id, created_at, updated_at
//	FROM challenges
//	WHERE id = ?
func (q *Queries) GetChallengeById(ctx context.Context, id int64) (Challenge, error) {
	row := q.queryRow(ctx, q.getChallengeByIdStmt, getChallengeById, id)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Difficulty,
		&i.Type,
		&i.TargetPattern,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChallenges = `-- name: ListChallenges :many
SELECT id, name, description, difficulty, type, target_pattern, user_id, created_at, updated_at
FROM challenges
ORDER BY created_at DESC
`

// ListChallenges
//
//	SELECT id, name, description, difficulty, type, target_pattern, user_id, created_at, updated_at
//	FROM challenges
//	ORDER BY created_at DESC
func (q *Queries) ListChallenges(ctx context.Context) ([]Challenge, error) {
	rows, err := q.query(ctx, q.listChallengesStmt, listChallenges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Challenge
	for rows.Next() {
		var i Challenge
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Difficulty,
			&i.Type,
			&i.TargetPattern,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChallenge = `-- name: UpdateChallenge :one
UPDATE challenges
SET name = ?,
    description = ?,
    difficulty = ?,
    type = ?,
    target_pattern = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, description, difficulty, type, target_pattern, user_id, created_at, updated_at
`

type UpdateChallengeParams struct {
	Name          string `json:"name"`
	Description   string `json:"description"`
	Difficulty    int64  `json:"difficulty"`
	Type          string `json:"type"`
	TargetPattern string `json:"target_pattern"`
	ID            int64  `json:"id"`
}

// UpdateChallenge
//
//	UPDATE challenges
//	SET name = ?,
//	    description = ?,
//	    difficulty = ?,
//	    type = ?,
//	    target_pattern = ?,
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE id = ?
//	RETURNING id, name, description, difficulty, type, target_pattern, user_id, created_at, updated_at
func (q *Queries) UpdateChallenge(ctx context.Context, arg UpdateChallengeParams) (Challenge, error) {
	row := q.queryRow(ctx, q.updateChallengeStmt, updateChallenge,
		arg.Name,
		arg.Description,
		arg.Difficulty,
		arg.Type,
		arg.TargetPattern,
		arg.ID,
	)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Difficulty,
		&i.Type,
		&i.TargetPattern,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
