// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clues.sql

package sqlc

import (
	"context"
)

const createClue = `-- name: CreateClue :one
INSERT INTO clues (
    challenge_id,
    description,
    sequence_order
)
VALUES (?, ?, ?)
RETURNING id, challenge_id, description, sequence_order, created_at, updated_at
`

type CreateClueParams struct {
	ChallengeID   int64
	Description   string
	SequenceOrder int64
}

func (q *Queries) CreateClue(ctx context.Context, arg CreateClueParams) (Clue, error) {
	row := q.db.QueryRowContext(ctx, createClue, arg.ChallengeID, arg.Description, arg.SequenceOrder)
	var i Clue
	err := row.Scan(
		&i.ID,
		&i.ChallengeID,
		&i.Description,
		&i.SequenceOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCluesByChallengeId = `-- name: GetCluesByChallengeId :many
SELECT id, challenge_id, description, sequence_order, created_at, updated_at
FROM clues
WHERE challenge_id = ?
ORDER BY sequence_order ASC
`

func (q *Queries) GetCluesByChallengeId(ctx context.Context, challengeID int64) ([]Clue, error) {
	rows, err := q.db.QueryContext(ctx, getCluesByChallengeId, challengeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Clue
	for rows.Next() {
		var i Clue
		if err := rows.Scan(
			&i.ID,
			&i.ChallengeID,
			&i.Description,
			&i.SequenceOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
