// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feedbacks.sql

package sqlc

import (
	"context"
	"encoding/json"
)

const createFeedback = `-- name: CreateFeedback :one
INSERT INTO feedbacks (
    score,
    rating,
    summary,
    suggestions
)
VALUES (?, ?, ?, ?)
RETURNING id, score, rating, summary, json(suggestions), created_at, updated_at
`

type CreateFeedbackParams struct {
	Score       int64           `json:"score"`
	Rating      int64           `json:"rating"`
	Summary     string          `json:"summary"`
	Suggestions json.RawMessage `json:"suggestions"`
}

// CreateFeedback
//
//	INSERT INTO feedbacks (
//	    score,
//	    rating,
//	    summary,
//	    suggestions
//	)
//	VALUES (?, ?, ?, ?)
//	RETURNING id, score, rating, summary, json(suggestions), created_at, updated_at
func (q *Queries) CreateFeedback(ctx context.Context, arg CreateFeedbackParams) (Feedback, error) {
	row := q.queryRow(ctx, q.createFeedbackStmt, createFeedback,
		arg.Score,
		arg.Rating,
		arg.Summary,
		arg.Suggestions,
	)
	var i Feedback
	err := row.Scan(
		&i.ID,
		&i.Score,
		&i.Rating,
		&i.Summary,
		&i.Suggestions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFeedbackById = `-- name: GetFeedbackById :one
SELECT id, score, rating, summary, json(suggestions), created_at, updated_at
FROM feedbacks
WHERE id = ?
`

// GetFeedbackById
//
//	SELECT id, score, rating, summary, json(suggestions), created_at, updated_at
//	FROM feedbacks
//	WHERE id = ?
func (q *Queries) GetFeedbackById(ctx context.Context, id int64) (Feedback, error) {
	row := q.queryRow(ctx, q.getFeedbackByIdStmt, getFeedbackById, id)
	var i Feedback
	err := row.Scan(
		&i.ID,
		&i.Score,
		&i.Rating,
		&i.Summary,
		&i.Suggestions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
