// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feedbacks.sql

package sqlc

import (
	"context"
)

const createFeedback = `-- name: CreateFeedback :one
INSERT INTO feedbacks (
    score,
    summary,
    suggestions
)
VALUES ( ?, ?, ?)
RETURNING id, score, summary, suggestions, created_at, updated_at
`

type CreateFeedbackParams struct {
	Score       int64  `json:"score"`
	Summary     string `json:"summary"`
	Suggestions string `json:"suggestions"`
}

// CreateFeedback
//
//	INSERT INTO feedbacks (
//	    score,
//	    summary,
//	    suggestions
//	)
//	VALUES ( ?, ?, ?)
//	RETURNING id, score, summary, suggestions, created_at, updated_at
func (q *Queries) CreateFeedback(ctx context.Context, arg CreateFeedbackParams) (Feedback, error) {
	row := q.queryRow(ctx, q.createFeedbackStmt, createFeedback, arg.Score, arg.Summary, arg.Suggestions)
	var i Feedback
	err := row.Scan(
		&i.ID,
		&i.Score,
		&i.Summary,
		&i.Suggestions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFeedbackById = `-- name: GetFeedbackById :one
SELECT id, score, summary, suggestions, created_at, updated_at
FROM feedbacks
WHERE id = ?
`

// GetFeedbackById
//
//	SELECT id, score, summary, suggestions, created_at, updated_at
//	FROM feedbacks
//	WHERE id = ?
func (q *Queries) GetFeedbackById(ctx context.Context, id int64) (Feedback, error) {
	row := q.queryRow(ctx, q.getFeedbackByIdStmt, getFeedbackById, id)
	var i Feedback
	err := row.Scan(
		&i.ID,
		&i.Score,
		&i.Summary,
		&i.Suggestions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
