// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"encoding/json"
	"time"
)

type Attempt struct {
	ID              int64
	UserChallengeID int64
	FeedbackID      interface{}
	Status          string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Challenge struct {
	ID            int64
	Name          string
	Description   string
	Difficulty    int64
	Type          string
	TargetPattern string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Clue struct {
	ID            int64
	ChallengeID   int64
	Description   string
	SequenceOrder int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Feedback struct {
	ID          int64
	Score       int64
	Rating      int64
	Summary     string
	Suggestions json.RawMessage
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID        int64
	Username  string
	Email     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type UserChallenge struct {
	ID          int64
	UserID      int64
	ChallengeID int64
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	CompletedAt interface{}
}
