// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"
)

type Attempt struct {
	ID            int64      `json:"id"`
	ChallengeID   int64      `json:"challenge_id"`
	FeedbackID    *int64     `json:"feedback_id"`
	Status        string     `json:"status"`
	SequenceOrder int64      `json:"sequence_order"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
	CompletedAt   *time.Time `json:"completed_at"`
}

type Challenge struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Difficulty  string    `json:"difficulty"`
	Type        string    `json:"type"`
	Target      string    `json:"target"`
	UserID      int64     `json:"user_id"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Clue struct {
	ID            int64     `json:"id"`
	ChallengeID   int64     `json:"challenge_id"`
	Description   string    `json:"description"`
	SequenceOrder int64     `json:"sequence_order"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type Feedback struct {
	ID          int64     `json:"id"`
	Score       int64     `json:"score"`
	Summary     string    `json:"summary"`
	Suggestions string    `json:"suggestions"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type User struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
