// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	//CreateAttempt
	//
	//  INSERT INTO attempts (
	//      feedback_id,
	//      challenge_id,
	//      status
	//  )
	//  VALUES (?, ?, ?)
	//  RETURNING id, challenge_id, feedback_id, status, created_at, updated_at, completed_at
	CreateAttempt(ctx context.Context, arg CreateAttemptParams) (Attempt, error)
	//CreateChallenge
	//
	//  INSERT INTO challenges (
	//      name,
	//      description,
	//      difficulty,
	//      type,
	//      target_pattern,
	//      user_id
	//  )
	//  VALUES (?, ?, ?, ?, ?, ?)
	//  RETURNING id, name, description, difficulty, type, target_pattern, user_id, created_at, updated_at
	CreateChallenge(ctx context.Context, arg CreateChallengeParams) (Challenge, error)
	//CreateClue
	//
	//  INSERT INTO clues (
	//      challenge_id,
	//      description,
	//      sequence_order
	//  )
	//  VALUES (?, ?, ?)
	//  RETURNING id, challenge_id, description, sequence_order, created_at, updated_at
	CreateClue(ctx context.Context, arg CreateClueParams) (Clue, error)
	//CreateFeedback
	//
	//  INSERT INTO feedbacks (
	//      score,
	//      summary,
	//      suggestions
	//  )
	//  VALUES ( ?, ?, ?)
	//  RETURNING id, score, summary, json(suggestions), created_at, updated_at
	CreateFeedback(ctx context.Context, arg CreateFeedbackParams) (Feedback, error)
	//CreateUser
	//
	//  INSERT INTO users (
	//      username,
	//      email
	//  )
	//  VALUES (?, ?)
	//  RETURNING id, username, email, created_at, updated_at
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	//GetAttemptById
	//
	//  SELECT id, challenge_id, feedback_id, status, created_at, updated_at, completed_at
	//  FROM attempts
	//  WHERE id = ?
	GetAttemptById(ctx context.Context, id int64) (Attempt, error)
	//GetChallengeById
	//
	//  SELECT id, name, description, difficulty, type, target_pattern, user_id, created_at, updated_at
	//  FROM challenges
	//  WHERE id = ?
	GetChallengeById(ctx context.Context, id int64) (Challenge, error)
	//GetCluesByChallengeId
	//
	//  SELECT id, challenge_id, description, sequence_order, created_at, updated_at
	//  FROM clues
	//  WHERE challenge_id = ?
	//  ORDER BY sequence_order ASC
	GetCluesByChallengeId(ctx context.Context, challengeID int64) ([]Clue, error)
	//GetFeedbackById
	//
	//  SELECT id, score, summary, json(suggestions), created_at, updated_at
	//  FROM feedbacks
	//  WHERE id = ?
	GetFeedbackById(ctx context.Context, id int64) (Feedback, error)
	//GetUserById
	//
	//  SELECT id, username, email, created_at, updated_at
	//  FROM users
	//  WHERE id = ?
	GetUserById(ctx context.Context, id int64) (User, error)
	//GetUserByUsername
	//
	//  SELECT id, username, email, created_at, updated_at
	//  FROM users
	//  WHERE username = ?
	GetUserByUsername(ctx context.Context, username string) (User, error)
	// This query fetches the attemps made by a specific user for a specific challenge.
	// It can be used to track the progress of a user on a particular challenge
	// It is obtained joinning the table challenges with the attempts table, filtering by user_id and challenge_id.
	//
	//  SELECT attempts.id, challenge_id, feedback_id, status, attempts.created_at, attempts.updated_at, completed_at, challenges.id, name, description, difficulty, type, target_pattern, user_id, challenges.created_at, challenges.updated_at
	//  FROM attempts
	//  JOIN challenges ON attempts.challenge_id = challenges.id
	//  WHERE challenges.user_id = ? AND challenges.id = ?
	//  ORDER BY attempts.created_at DESC
	ListAttemptsByUserChallenge(ctx context.Context, arg ListAttemptsByUserChallengeParams) ([]ListAttemptsByUserChallengeRow, error)
	//ListChallenges
	//
	//  SELECT id, name, description, difficulty, type, target_pattern, user_id, created_at, updated_at
	//  FROM challenges
	//  ORDER BY created_at DESC
	ListChallenges(ctx context.Context) ([]Challenge, error)
	//ListCluesByChallengeId
	//
	//  SELECT id, challenge_id, description, sequence_order, created_at, updated_at
	//  FROM clues
	//  WHERE challenge_id = ?
	//  ORDER BY sequence_order ASC
	ListCluesByChallengeId(ctx context.Context, challengeID int64) ([]Clue, error)
	//ListUserChallenges
	//
	//  SELECT id, name, description, difficulty, type, target_pattern, user_id, created_at, updated_at
	//  FROM challenges
	//  WHERE user_id = ?
	//  ORDER BY created_at DESC
	ListUserChallenges(ctx context.Context, userID int64) ([]Challenge, error)
	//ListUsers
	//
	//  SELECT id, username, email, created_at, updated_at
	//  FROM users
	//  ORDER BY created_at DESC
	ListUsers(ctx context.Context) ([]User, error)
	//UpdateAttempt
	//
	//  UPDATE attempts
	//  SET feedback_id = ?,
	//      status = ?,
	//      completed_at = CURRENT_TIMESTAMP
	//  WHERE id = ?
	//  RETURNING id, challenge_id, feedback_id, status, created_at, updated_at, completed_at
	UpdateAttempt(ctx context.Context, arg UpdateAttemptParams) (Attempt, error)
	//UpdateChallenge
	//
	//  UPDATE challenges
	//  SET name = ?,
	//      description = ?,
	//      difficulty = ?,
	//      type = ?,
	//      target_pattern = ?,
	//      updated_at = CURRENT_TIMESTAMP
	//  WHERE id = ?
	//  RETURNING id, name, description, difficulty, type, target_pattern, user_id, created_at, updated_at
	UpdateChallenge(ctx context.Context, arg UpdateChallengeParams) (Challenge, error)
	//UpdateUser
	//
	//  UPDATE users
	//  SET username = ?, email = ?
	//  WHERE id = ?
	//  RETURNING id, username, email, created_at, updated_at
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
