// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_challenges.sql

package sqlc

import (
	"context"
)

const createUserChallenge = `-- name: CreateUserChallenge :one
INSERT INTO user_challenges (
    user_id,
    challenge_id,
    status
)
VALUES (?, ?, ?)
RETURNING id, user_id, challenge_id, status, created_at, updated_at, completed_at
`

type CreateUserChallengeParams struct {
	UserID      int64
	ChallengeID int64
	Status      string
}

func (q *Queries) CreateUserChallenge(ctx context.Context, arg CreateUserChallengeParams) (UserChallenge, error) {
	row := q.db.QueryRowContext(ctx, createUserChallenge, arg.UserID, arg.ChallengeID, arg.Status)
	var i UserChallenge
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChallengeID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getUserChallengeById = `-- name: GetUserChallengeById :one
SELECT id, user_id, challenge_id, status, created_at, updated_at, completed_at
FROM user_challenges
WHERE id = ?
`

func (q *Queries) GetUserChallengeById(ctx context.Context, id int64) (UserChallenge, error) {
	row := q.db.QueryRowContext(ctx, getUserChallengeById, id)
	var i UserChallenge
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChallengeID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getUserChallengesByChallengeId = `-- name: GetUserChallengesByChallengeId :many
SELECT id, user_id, challenge_id, status, created_at, updated_at, completed_at
FROM user_challenges
WHERE challenge_id = ?
ORDER BY created_at DESC
`

func (q *Queries) GetUserChallengesByChallengeId(ctx context.Context, challengeID int64) ([]UserChallenge, error) {
	rows, err := q.db.QueryContext(ctx, getUserChallengesByChallengeId, challengeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserChallenge
	for rows.Next() {
		var i UserChallenge
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ChallengeID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserChallengesByUserId = `-- name: GetUserChallengesByUserId :many
SELECT id, user_id, challenge_id, status, created_at, updated_at, completed_at
FROM user_challenges
WHERE user_id = ?
ORDER BY created_at DESC
`

func (q *Queries) GetUserChallengesByUserId(ctx context.Context, userID int64) ([]UserChallenge, error) {
	rows, err := q.db.QueryContext(ctx, getUserChallengesByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserChallenge
	for rows.Next() {
		var i UserChallenge
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ChallengeID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserChallengeStatus = `-- name: UpdateUserChallengeStatus :one
UPDATE user_challenges
SET status = ?
WHERE id = ?
RETURNING id, user_id, challenge_id, status, created_at, updated_at, completed_at
`

type UpdateUserChallengeStatusParams struct {
	Status string
	ID     int64
}

func (q *Queries) UpdateUserChallengeStatus(ctx context.Context, arg UpdateUserChallengeStatusParams) (UserChallenge, error) {
	row := q.db.QueryRowContext(ctx, updateUserChallengeStatus, arg.Status, arg.ID)
	var i UserChallenge
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChallengeID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}
