// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: challenges.sql

package sqlc

import (
	"context"
	"time"
)

const createChallenge = `-- name: CreateChallenge :one
INSERT INTO challenges (
    name,
    description,
    difficulty,
    type,
    target_pattern,
    status,
    created_at,
    updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, description, difficulty, type, target_pattern, status, created_at, updated_at
`

type CreateChallengeParams struct {
	Name          string
	Description   string
	Difficulty    string
	Type          string
	TargetPattern string
	Status        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) CreateChallenge(ctx context.Context, arg CreateChallengeParams) (Challenge, error) {
	row := q.db.QueryRowContext(ctx, createChallenge,
		arg.Name,
		arg.Description,
		arg.Difficulty,
		arg.Type,
		arg.TargetPattern,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Difficulty,
		&i.Type,
		&i.TargetPattern,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChallengeById = `-- name: GetChallengeById :one
SELECT id, name, description, difficulty, type, target_pattern, status, created_at, updated_at
FROM challenges
WHERE id = ?
`

func (q *Queries) GetChallengeById(ctx context.Context, id int64) (Challenge, error) {
	row := q.db.QueryRowContext(ctx, getChallengeById, id)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Difficulty,
		&i.Type,
		&i.TargetPattern,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChallenges = `-- name: ListChallenges :many
SELECT id, name, description, difficulty, type, target_pattern, status, created_at, updated_at
FROM challenges
ORDER BY created_at DESC
`

func (q *Queries) ListChallenges(ctx context.Context) ([]Challenge, error) {
	rows, err := q.db.QueryContext(ctx, listChallenges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Challenge
	for rows.Next() {
		var i Challenge
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Difficulty,
			&i.Type,
			&i.TargetPattern,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
