// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"
)

type Challenge struct {
	ID            int64
	Name          string
	Description   string
	Difficulty    string
	Type          string
	TargetPattern string
	Status        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
